#!/usr/bin/env python
"""
Create a CSV file from the output generated by algostat.py

Usage:
    create_csv.py -f FILE

Options:
    -h --help       Show this screen
    -f FILE         File to read in
"""
from operator import itemgetter

from docopt import docopt

from algorithm import ALGORITHMS


def print_header():
    print("\t".join(["repository"] + [algo for algo in sorted(ALGORITHMS)]))


def print_line(line):
    algorithms = {key: 0 for key in ALGORITHMS}
    columns = line.split(" ")
    repo = columns[0]

    for algo in columns[1:]:
        values = algo.split(":")
        algorithms[values[0]] += int(values[1])

    sorted_results = sorted(algorithms.items(), key=itemgetter(0))
    print("\t".join([repo] + [str(count) for algo, count in sorted_results]))

if __name__ == '__main__':
    args = docopt(__doc__)

    with open(args["-f"]) as fh:
        print_header()
        for line in fh:
            print_line(line)
